### ISSUE TITLE
bad argument #1 to 'GetBonePosition' (number expected, got no value)

### ISSUE THREAD

**Issue by jacobgc** [lolleko/guesswho#11]
[Guess Who] lua/effects/gw_stunned.lua:11: bad argument #1 to 'GetBonePosition' (number expected, got no value)
1. GetBonePosition - [C]:-1
   1. unknown - lua/effects/gw_stunned.lua:11

Don't know how this happend but it did ._.

**Comment by lolleko** [comment]
You right that shouldn't happen. But I also should have catched that exception. I did now so this should be fixed.
