### ISSUE TITLE
Players randomly getting this error

### ISSUE THREAD

**Issue by jacobgc** [lolleko/guesswho#12]
Error in hook HUDPaint: gamemodes/guesswho/gamemode/cl_hud.lua:116: attempt to call method 'Clip1' (a nil value)
stack traceback:
    gamemodes/guesswho/gamemode/cl_hud.lua:116: in function 'fn'
    addons/ulib/lua/ulib/shared/hook.lua:179: in function <addons/ulib/lua/ulib/shared/hook.lua:162>
    [C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
1. unknown - [C]:-1

**Comment by lolleko** [comment]
Should be fixed.
