### ISSUE TITLE
Customization...

### ISSUE THREAD

**Issue by TheRumTumTiger** [lolleko/guesswho#14]
I don't understand it. And I also can't find the paths you gave me. I have no idea what to do. Could you give a better guide please? OR maybe you can put in a customizer in your gamemode! Like you go into to play with friends and, admin get's to choose, you can open a window that says customize. Then you can just select a model you want to be in. There are slots of what player models you use.

**Comment by jacobgc** [comment]
You did not give the greates explanation of what you want. But I'll give it my best shot.

To change the playermodel of the seeker goto: addons/guesswho/gamemode/guesswho/gamemode/player_class/player_seeker.lua and change line 12 to the model you want. For example Kliner: local model = "models/player/kleiner.mdl"

To change the playermodels of the NPCs and hidden goto:
addons/guesswho/gamemode/guesswho/gamemode/sh_config.lua and change the table on line one to your liking: GM.Models = { }

EDIT: Just wrote what you put. That is a custom addon that the server is using to allow the players to change their playermodel. On a default server however you can press E on another NPC to change your playermodel.

**Comment by lolleko** [comment]
You should read the installation part first! If you don't use the source code or don't extract the gam you won't have this paths. The guide isn't really meant for beginners. I'm sorry but i don't have time to write a noob friendlier in depth guide atm.

-Lolle

Closed
