### ISSUE TITLE
Unable to add custom models.

### ISSUE THREAD

**Issue by RaccoonsFury** [lolleko/guesswho#17]
After deleting the defaults and adding custom models, it's still loading the defaults. The table looks like this.

GM.Models = {
"models/sinful/frisk.mdl",
"models/player/meeseeks/meeseeks.mdl",
"models/player/olddeath/saitama.mdl",
"models/player/alicede_sharkfurry.mdl",
"models/freeman/player/left_shark.mdl"
}

Anything off? Does there need to be at least X amount of them, does it need the entire file structure, or /addons/ before models maybe?

**Comment by jacobgc** [comment]
Your table is completely fine. Have you restarted your server? You need to if you have not.

I just want to clear something up. In your last sentance you said that maybee you need to add /addons/ before the models. you will never need to do that you see. When Garry's Mod mounts an addon, all of the addons files (lua, models, materials and all of that) can then be accessed directly from modles/ or materials/ or what ever the folder is!

**Comment by RaccoonsFury** [comment]
Yes... the server was restarted.

**Comment by jacobgc** [comment]
I don't want to sound rude but, did you save the file? We are humans, we all make mistakes. And the thing with the game mode, if you mess up the GM.Models table. You would get loads of errors instead of it using the default ones....

**Comment by RaccoonsFury** [comment]
... yes. The file was saved and the server was reset after the fact. I've run dedicated servers before and have the basics down. The server is also plugged in, while we're at it.

**Comment by lolleko** [comment]
Is the guess who gma in your addons folder aswell?

**Comment by RaccoonsFury** [comment]
Yes. We're able to play Guess Who, and it only displays the default models,
despite none of them being present in the above table.

**Comment by jacobgc** [comment]
The GMA file is just a packed version of the default gamemode. The game is loading the GMA which is overriding what you are editing. Remove the GMA from your server.

**Comment by lolleko** [comment]
+

**Comment by jacobgc** [comment]
Sniped :)

**Comment by RaccoonsFury** [comment]
I'll give that a shot.

**Comment by jacobgc** [comment]
If Guess Who? Is in your workshop collection your server will download the GMA again. Just sayin.

**Comment by Anomaladox** [comment]
The only thing I see wrong with the table:

After "models/freeman/player/left_shark.mdl" you need a comma.

So it has to look like this 
GM.Models = {
"models/sinful/frisk.mdl",
"models/player/meeseeks/meeseeks.mdl",
"models/player/olddeath/saitama.mdl",
"models/player/alicede_sharkfurry.mdl",
"models/freeman/player/left_shark.mdl",
}

you need a comma after each .mdl entry.

**Comment by jacobgc** [comment]
Anomaladox, you are wrong. The last line of the table does not require a comma after it.

**Comment by RaccoonsFury** [comment]
Alright, looks like deleting the .gma and removing it from the workshop collection did it. Thanks!

**Comment by jacobgc** [comment]
Glad to hear you got it working!

**Comment by datdude813** [comment]
I'm struggling with it too, if you can help me please add me on discord
