### ISSUE TITLE
Why aren't and NPC's spawning in my guess who server.

### ISSUE THREAD

**Issue by ghost** [lolleko/guesswho#24]
I started a guesswho server in gmod. Everything works perfectly except that no NCP's spawn so it's just me and my friend and it's boring without NPC's. I downloaded the server files from GitHub itself. Any suggestions? And how do I load in coustom NPC packs? If you can, please give the link to the right server files for gmod.

**Comment by lolleko** [comment]
Read teh wiki! where did you  put the download?

**Comment by ghost** [comment]
Thanks dude. whenever it typed guess who wiki gmod i got nothing relevant thanks a lot dude

**Comment by ghost** [comment]
OK ive downloaded the correct files from the wiki but the NPC won't spawn.
do I have to put the player models I want in game in the addons folder of
the server ,or change the game mode coding to the NPC skin's that I want
On May 4, 2016 4:09 PM, "lolleko" notifications@github.com wrote:

Closed #24 https://github.com/lolleko/guesswho/issues/24.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
https://github.com/lolleko/guesswho/issues/24#event-650008828
