### ISSUE TITLE
Problem with private server for Gmod for gamemodes guess who and hide and sneak (not prop hunt)

### ISSUE THREAD

**Issue by ghost** [lolleko/guesswho#35]
I have posted a similar question once before but I can't seem to find it.
1. Why won't NPC's spawn in my guess who private server i have all the correct server files but am I supposed to put the NPC's I want in the game mode in the addons folder of the server? I have seen a. Video to how to add custom NPC'S in guess who and tried it but the NPC still won't spawn. Any suggestions if there is one please send a video link.
1. Can somebody provide me with the server files for hide and seek and murderer because I can't find working ones anywhere. Working for 2016 may. Thanks a lot guys

**Comment by lolleko** [comment]
If you downblaod the zip here, the ziup has to go into the addons folder not the gamemodes folder as described here: https://github.com/lolleko/guesswho/wiki/installation

As for your other question i cant help you i dont have those files anymore either.

**Comment by ghost** [comment]
Thanks a lot

**Comment by ghost** [comment]
Thanks
