### ISSUE TITLE
Getting Custom Player Models To Work

### ISSUE THREAD

**Issue by ItzFreddo** [lolleko/guesswho#37]
Hello i have added all the custom models in the config
GM.Models = {
 --Characters
    "models/player/big_dew.mdl",
    "models/Splinks/KF2/characters/Arms_Foster.mdl",
    "models/player/Jenssons/toad.mdl",
    "models/player_zsssamusu.mdl",
    "models/player_ashe.mdl",
    "models/player/tfa_irons_playercolor.mdl",
    "models/player/chewie.mdl",
    "models/player/han_solo.mdl",
    "models/mark2580/borderlands_ps/moxxi_moon.mdl",
    "models/player/ilbe/noala.mdl"

But when i load up the game they are all default. i understand that its in my collection i have the guesswho  addon but when i dont have it the server will not allow us to pick a team.
i have installed the gamemode on to my server.
https://gyazo.com/60d335cc629e93b344a7ae68d66c6630
And on your help page you say to remove the gma. but when i look there are no files with a .gma.

**Comment by lolleko** [comment]
The gamemode is an addon and therefore you have to copy it do your addons/ directory not gamemodes/

This is described on the "Install" wiki page.

**Comment by jacobgc** [comment]
Why do people not read....

**Comment by ItzFreddo** [comment]
the thing is i do read....
and i have it in my addons folder yet still nothing works...
https://gyazo.com/b06eee353c3c0075d4fae547ff7cbfed
https://gyazo.com/cbe5a720a4c26b4424ec7b95c3d1864f
