### ISSUE TITLE
Player does not stay up after sitting

### ISSUE THREAD

**Issue by CattoGamer** [lolleko/guesswho#40]
As described above, it is around here that the player no longer stays up after sitting.

These are the models for the NPC's (playermodel' ofc used for this part)
http://steamcommunity.com/sharedfiles/filedetails/?id=107155115

And here the models in the sh_config

> GM.Models = {
>     "models/trixie_player.mdl",
>     "models/derpyhooves_player.mdl",
>     "models/lyra_player.mdl",
>     "models/rainbowdash_player.mdl",
>     "models/fluttershy_player.mdl",
>     "models/pinkiepie_player.mdl",
>     "models/rarity_player.mdl",
>     "models/applejack_player.mdl",
>     "models/bonbon_player.mdl",
>     "models/colgate_player.mdl",
>     "models/vinyl_player.mdl",
>     "models/raindrops_player.mdl",
>     "models/daringdoo_player.mdl",
>     "models/spitfire_player.mdl",
>     "models/roseluck_player.mdl",
>     "models/octavia_player.mdl",
>     "models/princesstwilight_player.mdl",
> }

These playermodels are custom and do not use the "sit_zen" sequence, their are using "sit".
I edited in sh_animations the LookupSequence "sit_zen" to "sit" and YAY! it did worked,but now the Player stays always in the Sit animation and wont return back to normal state...

If the NPC's are sitting their is any probelm of returning back to normal state. (their staying up and walking, for the player not)

**Comment by N-SA** [comment]
Bloody brony
On 6 Jul 2016 21:59, "Shadowsun™" <notifications@github.com> wrote:
>
> As described above, it is around here that the player no longer stays up
after sitting.
>
> These are the models for the NPC's (playermodel' ofc used for this part)
> http://steamcommunity.com/sharedfiles/filedetails/?id=107155115
>
> And here the models in the sh_config
>>
>> GM.Models = {
>> "models/trixie_player.mdl",
>> "models/derpyhooves_player.mdl",
>> "models/lyra_player.mdl",
>> "models/rainbowdash_player.mdl",
>> "models/fluttershy_player.mdl",
>> "models/pinkiepie_player.mdl",
>> "models/rarity_player.mdl",
>> "models/applejack_player.mdl",
>> "models/bonbon_player.mdl",
>> "models/colgate_player.mdl",
>> "models/vinyl_player.mdl",
>> "models/raindrops_player.mdl",
>> "models/daringdoo_player.mdl",
>> "models/spitfire_player.mdl",
>> "models/roseluck_player.mdl",
>> "models/octavia_player.mdl",
>> "models/princesstwilight_player.mdl",
>> }
>
> These playermodels are custom and do not use the "sit_zen" sequence,
their are using "sit".
> I edited in sh_animations the LookupSequence "sit_zen" to "sit" and YAY!
it did worked,but now the Player stays always in the Sit animation and wont
return back to normal state...
>
> If the NPC's are sitting their is any probelm of returning back to normal
state. (their staying up and walking, for the player not)

**Comment by jacobgc** [comment]
Fakin brony.

**Comment by jacobgc** [comment]
From what I can gather you could do 2 things. 

1) remove the shitty player models that use 'sit'
2) create a script that determins the player model and uses the correct a nation sequence.

**Comment by lolleko** [comment]
The sequence `sit` won't work. Possible solutions:

3) Try different sequences "idle_cower_all" for example you can retrieve a full list of sequences of your current player model with the command: `lua_run PrintTable(Entity(1):GetSequenceList())`

4) Difficulty: Restore the players original crouching behaviour by deleting GM:HandlePlayerDucking() and modifying `lua/entities/npc_walker.lua;ENT:Sit()` to use `self:SetActivity(ACT_MP_CROUCH_IDLE)` instead of `self:SetSequence()`.

But i suggest you use supported models. I think there are ponies on the workshop that are supported if i remember correctly.

**Comment by CattoGamer** [comment]
1) Dear @N-SA please Just go and hang yourself, No one has asked you to Support!
2) @lolleko first thank you for the helpful answer, I 'll try it now if it goes and yes the model is supported

**Comment by jacobgc** [comment]
@FarukGamer It's funny cause the dev suggested the exact same things I did....

**Comment by CattoGamer** [comment]
Es ist doch scheiß egal jetzt... Ich konnte das problem lösen :)

Hier http://pastebin.com/qD900Yig
Sollte nützlich sein für andere Server.

**Comment by lolleko** [comment]
GJ maybe i will add that to support playermodels that dont have a sit_zen anim.

**Comment by jacobgc** [comment]
"It's a shit now ... I could solve the problem :)" -- Thanks google translate. I'm not sure that's what he said though...

**Comment by CattoGamer** [comment]
@N-SA let me explain it in english for you :D

> nevermind... i solved the poblem :)

**Comment by jacobgc** [comment]
@FarukGamer Wow, google really fucked up that translation...

**Comment by CattoGamer** [comment]
@N-SA indeed
