### ISSUE TITLE
Map not changing after 10 round pass

### ISSUE THREAD

**Issue by KnottyCord** [lolleko/guesswho#43]
Every thing is in the title!

Thank you
Shawn Mercier aka KnottyCord

**Comment by lolleko** [comment]
Not changing to a different map or not changing at all?

**Comment by KnottyCord** [comment]
Not changing at all. My server does go to the changing level loading screen but after it the exact  same map over and over.

Ps: The game mode is running in a decayed server.

**Comment by lolleko** [comment]
You have to tell the game which maps it can switch too.
Create `garrysmod/cfg/mapcycle.txt`
