### ISSUE TITLE
Spamming F2 increases timer

### ISSUE THREAD

**Issue by bobby-swetz** [lolleko/guesswho#47]
Not sure if this is an issue or it's intentional, but if you keep clicking F2 after it's told you it's too soon, the timer begins to increase.
`Please wait 11 more seconds before trying to change team again
Please wait 12 more seconds before trying to change team again
Please wait 13 more seconds before trying to change team again
Please wait 13 more seconds before trying to change team again
Please wait 14 more seconds before trying to change team again
Please wait 15 more seconds before trying to change team again
Please wait 16 more seconds before trying to change team again
Please wait 17 more seconds before trying to change team again
Please wait 17 more seconds before trying to change team again
Please wait 18 more seconds before trying to change team again
Please wait 19 more seconds before trying to change team again`

**Comment by jacobgc** [comment]
`if ( ply.LastTeamSwitch and RealTime() - ply.LastTeamSwitch < TimeBetweenSwitches ) then
        ply.LastTeamSwitch = ply.LastTeamSwitch + 1
        ply:ChatPrint( Format( "Please wait %i more seconds before trying to change team again", ( TimeBetweenSwitches - ( RealTime() - ply.LastTeamSwitch ) ) + 1 ) )
        return false
    end`

As you can see here. If someone tries to change team before the timer runs down. it will add another second onto the timer using the line below.
`ply.LastTeamSwitch = ply.LastTeamSwitch + 1`

So more than likely, this is intentional.

**Comment by lolleko** [comment]
It's intended it's used to prevent team switch spam. Although it might be a bit buggy.

**Comment by lolleko** [comment]
Will close this as this is not really a issue. Just dont spam F2.
