### ISSUE TITLE
Crashing on 1.6.4

### ISSUE THREAD

**Issue by bobby-swetz** [lolleko/guesswho#49]
GMod crashes after loading into the server when the Info Menu pops up on 1.6.4. Reverting back to 1.6.2 and reenabling hunter names manually has had no issues so far.

Server is dedicated running on a Linux box.

**Comment by lolleko** [comment]
what info menu o you mean?

**Comment by CattoGamer** [comment]
Its seems related to the latest Garry's Mod update. This can also caused by some addons.

**Comment by lolleko** [comment]
Any errors or a crash dump maybe?

**Comment by bobby-swetz** [comment]
Crash dump: http://dumps.metastruct.uk.to/dumper.py?dump=hl2_170417_crash_2017_4_21T5_7_3C0.mdmp

Didn't really see any errors that stuck out to me. And for the info menu I mean the menu that first appears on connect that shows update information as well as choosing your team.

**Comment by lolleko** [comment]
Well the stack confirms that the thread crashed because of lua and vgui. I will look into it. Must be related to the info box i added.
