### ISSUE TITLE
Hiding timer set for an hour?

### ISSUE THREAD

**Issue by ajgeiss0702** [lolleko/guesswho#50]
In the current version, when the round starts, the hiding timer which should be 30 seconds is an hour. The seekers are also blinded for this time, so it breaks the game. Please fix asap!

**Comment by jacobgc** [comment]
Last time I checked the value is set in the config. So look there and change it

**Comment by ajgeiss0702** [comment]
Where is it? I checked in sh_config.lua and cant find it

**Comment by jacobgc** [comment]
{

			"name"		"gw_pregameduration"

			"text"		"The delay after map change"

			"help"		"The duration of the pause after a map change in seconds."

			"type"		"Numeric"

			"default"	"20"

		}

		6

		{

			"name"		"gw_roundduration"

			"text"		"The round duration"

			"help"		"The duration of a round (Seeking) in seconds"

			"type"		"Numeric"

			"default"	"300"

		}

		7

		{

			"name"		"gw_hideduration"

			"text"		"The hide duration"

			"help"		"The time that the hiding team gets to disappear in seconds."

			"type"		"Numeric"

			"default"	"30"


From what I've seen they are set with these cars. Socvatd if this looks horid. I'm trying to do this on my phone

**Comment by ajgeiss0702** [comment]
Thanks, I will try that in a minute

**Comment by jacobgc** [comment]
Wow, that comment bugged out, anyway, I feel like you got the idea of what I was trying to say.

It may be you've accidentally set them somewhere without knowing.

**Comment by ajgeiss0702** [comment]
Nope, it is set to 30, and it still makes the time as an hour

**Comment by jacobgc** [comment]
Hmm. This is odd. Gonna have to leave it for @lolleko to take a look at, sorry.

**Comment by ajgeiss0702** [comment]
Ok, thanks anyway!

**Comment by ajgeiss0702** [comment]
It just started working! Maybe restarting the server once wasn't enough :P
