### ISSUE TITLE
Sudoku issue

### ISSUE THREAD

**Issue by stealth23k** [lolleko/guesswho#62]
Hi i was unable to find a fix for this and i am not even sure if you are active but im having an issue with the sudoku ability i get this error [Guess Who] gamemodes/guesswho/entities/weapons/weapon_gw_sudoku.lua:38: bad argument #1 to 'SetOwner' (Entity expected, got userdata)
  1. SetOwner - [C]:-1
   2. unknown - gamemodes/guesswho/entities/weapons/weapon_gw_sudoku.lua:38

Timer Failed! [Simple][@gamemodes/guesswho/entities/weapons/weapon_gw_sudoku.lua (line 32)]
Now i have no idea what this means as the rest of the gamemode works fine an help would be appreciated

**Comment by stealth23k** [comment]
@lolleko sorry if you are busy etc im trying to play the game mode with some friends and that's why i ask

**Comment by lolleko** [comment]
Hey, you don't have to apologise! But I am indeed a bit busy at the moment.

A Bugfix patch is something that I have planned for this year once I have some more time.
Thanks for the detailed report!

**Comment by stealth23k** [comment]
No problem thank you for the quick reply I hope its soon haha the gamemode is really fun with friends it's a shame not many people are playing it on the live servers
