### ISSUE TITLE
Walking into an NPC causes them to stop moving.

### ISSUE THREAD

**Issue by jacobgc** [lolleko/guesswho#8]
Like the title says. When a player touches an NPC the NPC stops moving completely. Making it easy to tell an NPC from a player.

**Comment by rafraser** [comment]
If you're a player you're able to mimic this behaviour. True skill is recongizing little quirks like these, and acting accordingly based on them.

**Comment by jacobgc** [comment]
Its not the easyist thing to mimic as from the third person perspective it is hard to tell when the seeker is touching you. I am also being called a hacker by half of the server when I use this quirk.

**Comment by lolleko** [comment]
Issue delayed until the nexbots there is a patch for nextbots collisions.
