### ISSUE TITLE
picked up items drop when touching NPC

### ISSUE THREAD

**Issue by jacobgc** [lolleko/guesswho#9]
Like the title says, a picked up object will drop instantly when it touches an NPC. It does not do this if it touches a player however.

**Comment by lolleko** [comment]
That's weird because the object should drop if touching a player. Maybe you can find the issue 4 eyes are better then 2 :D 

``` lua
function GM:ShouldCollide( ent1, ent2 )
    if ( ent1:IsPlayerHolding() or ent2:IsPlayerHolding() ) and (ent1:GetClass() == "npc_walker" or ent2:GetClass() == "npc_walker" or ( ent1:IsPlayer() and ent1:Team() == TEAM_HIDING ) or( ent2:IsPlayer() and ent2:Team() == TEAM_HIDING )  ) then
        DropEntityIfHeld( ent1 )
        DropEntityIfHeld( ent2 )
    end
    return true
end
```

line 76-82 shared.lua

**Comment by jacobgc** [comment]
Well. They do drop on the player, but it requires a lot more force.

**Comment by jacobgc** [comment]
Any reason why the props only drop if ent1/ent2 is touching a hider? Why not make it drop when it touches a seeker too?

**Comment by lolleko** [comment]
The object now drops on all players. Also it shouldn't launch away as much if it hits a npc.
Fixed.
